FROM alpine:latest as builder
RUN apk add --no-cache gettext

FROM prom/prometheus:latest
COPY --from=builder /usr/bin/envsubst /usr/bin/envsubst
COPY --from=builder /usr/lib/libintl.so.8 /usr/lib/libintl.so.8
COPY --from=builder /lib/ld-musl-* /lib/
