user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream docker-eeos-backend {
        server eeos-backend:8080;
    }

    # 기존 도메인(.store)에 대한 리다이렉트
    server {
        listen 80;
        server_name eeos.store;
        return 301 http://eeos.co.kr$request_uri;
    }

    # 새 도메인(.co.kr) 처리
    server {
        listen 80;
        server_name eeos.co.kr;

        location /api/ {
            proxy_pass http://docker-eeos-backend/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    access_log  /var/log/nginx/access.log;
    sendfile        on;
    keepalive_timeout  65;
}
