spring:
  config:
    activate:
      on-profile: local-mysql
  datasource:
    url: jdbc:mysql://localhost:13308/eeos?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true?setTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    sql: debug