spring:
  config:
    activate:
      on-profile: actuator

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, metrics
      base-path: "/actuator"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: eeos
