spring:
  profiles:
    group:
      local:
        - local-mysql
        - api
        - oauth
        - token
        - actuator
        - local-redis
        - swagger
      dev:
        - mysql
        - api
        - oauth
        - token
        - log
        - actuator
        - redis
        - swagger
      prod:
        - mysql
        - api
        - oauth
        - token
        - log
        - actuator
        - redis
        - swagger
    active: local