spring:
  profiles:
    group:
      local:
        - local-mysql
        - api
        - oauth
        - token
        - actuator
        - local-redis
        - slack
        - swagger
        - admin
      dev:
        - mysql
        - api
        - oauth
        - token
        - log
        - actuator
        - redis
        - swagger
        - slack
        - admin
      prod:
        - mysql
        - api
        - oauth
        - token
        - log
        - actuator
        - redis
        - slack
        - admin
    active: local