spring:
  config:
    activate:
      on-profile: local-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/eeos?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: gksktodaud1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    open-in-view: false
  flyway:
    baseline-on-migrate: false
    enabled: true
    baseline-version: 0
    out-of-order: true
    url: jdbc:mysql://localhost:3306/eeos?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    user: root
    password: gksktodaud1!

logging:
  level:
    root: info

