spring:
  config:
    activate:
      on-profile: slack

slack:
  bot:
    black-company:
      eeos-bot: ${BLACK_COMPANY_EEOS_BOT_TOKEN}
    econovation:
      eeos-bot: ""

  channel:
    black-company:
      eeos-test: ${BLACK_COMPANY_CHANNEL_ID}
    econovation:
      notification: ${ECONOVATION_NOTIFICATION_CHANNEL_ID}
